spring.application.name=Search
server.port=8088

################################
# Logging
################################
logging.config=classpath:logback-spring.xml


################################
# Jackson / Encoding (선택)
################################
spring.jackson.time-zone=Asia/Seoul
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true


