spring.application.name=Search
server.port=8088

#Psql
spring.datasource.hikari.driver-class-namer=org.postgresql.Driver
spring.datasource.hikari.jdbcUrl=jdbc:postgresql://localhost:5432/user_info?serverTimeZone=UTC&CharacterEncoding=UTF-8
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=YNJW375812!
spring.datasource.hikari.maximum-pool-size= 10
spring.datasource.hikari.connection-timeout= 5000
spring.datasource.hikari.connection-init-sql= SELECT 1
spring.datasource.hikari.validation-timeout= 2000
spring.datasource.hikari.minimum-idle= 10
spring.datasource.hikari.idle-timeout= 600000
spring.datasource.hikari.max-lifetime: 1800000
