spring.application.name=Search
server.port=${SERVER_PORT:8088}

# PostgreSQL (Search DB)
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbcUrl=${SEARCH_DB_URL:jdbc:postgresql://localhost:5432/user_info?serverTimeZone=UTC&CharacterEncoding=UTF-8}
spring.datasource.hikari.username=${SEARCH_DB_USERNAME:postgres}
spring.datasource.hikari.password=${SEARCH_DB_PASSWORD}

# Hikari
spring.datasource.hikari.maximum-pool-size=${SEARCH_DB_MAX_POOL_SIZE:10}
spring.datasource.hikari.connection-timeout=${SEARCH_DB_CONNECTION_TIMEOUT:5000}
spring.datasource.hikari.connection-init-sql=${SEARCH_DB_CONNECTION_INIT_SQL:SELECT 1}
spring.datasource.hikari.validation-timeout=${SEARCH_DB_VALIDATION_TIMEOUT:2000}
spring.datasource.hikari.minimum-idle=${SEARCH_DB_MINIMUM_IDLE:10}
spring.datasource.hikari.idle-timeout=${SEARCH_DB_IDLE_TIMEOUT:600000}
spring.datasource.hikari.max-lifetime=${SEARCH_DB_MAX_LIFETIME:1800000}
